
config { type: "table" }

SELECT 11 as col1, "k" as col2, true as col3, 3.1 as col4, DATE("2023-03-01") as col5, TIMESTAMP("2023-03-01 12:00:00") as col6, "foo" as col7, 1100 as col8, "p" as col9, "source3" as col10
UNION ALL
SELECT 12, "l", false, 3.2, DATE("2023-03-02"), TIMESTAMP("2023-03-02 12:00:00"), "bar", 1200, "o", "source3"
UNION ALL
SELECT 13, "m", true, 3.3, DATE("2023-03-03"), TIMESTAMP("2023-03-03 12:00:00"), "baz", 1300, "n", "source3"
UNION ALL
SELECT 14, "n", false, 3.4, DATE("2023-03-04"), TIMESTAMP("2023-03-04 12:00:00"), "qux", 1400, "m", "source3"
UNION ALL
SELECT 15, "o", true, 3.5, DATE("2023-03-05"), TIMESTAMP("2023-03-05 12:00:00"), "quux", 1500, "l", "source3"
