
config { type: "table" }

SELECT 1 as col1, "a" as col2, true as col3, 1.1 as col4, DATE("2023-01-01") as col5, TIMESTAMP("2023-01-01 12:00:00") as col6, "foo" as col7, 100 as col8, "x" as col9, "source1" as col10
UNION ALL
SELECT 2, "b", false, 1.2, DATE("2023-01-02"), TIMESTAMP("2023-01-02 12:00:00"), "bar", 200, "y", "source1"
UNION ALL
SELECT 3, "c", true, 1.3, DATE("2023-01-03"), TIMESTAMP("2023-01-03 12:00:00"), "baz", 300, "z", "source1"
UNION ALL
SELECT 4, "d", false, 1.4, DATE("2023-01-04"), TIMESTAMP("2023-01-04 12:00:00"), "qux", 400, "w", "source1"
UNION ALL
SELECT 5, "e", true, 1.5, DATE("2023-01-05"), TIMESTAMP("2023-01-05 12:00:00"), "quux", 500, "v", "source1"
