
config {
  type: "table",
  name: "bad_performance_query"
}

SELECT
    q.id AS question_id,
    q.title,
    q.body as question_body,
    a.id AS answer_id,
    a.body as answer_body
FROM
    ${ref("posts_questions")} AS q,
    ${ref("posts_answers")} AS a
WHERE
    q.id = a.parent_id
    AND q.id IN (
        SELECT id
        FROM ${ref("posts_questions")}
        WHERE favorite_count > 100
    )
    AND CONCAT('|', q.tags, '|') LIKE '%|bigquery|%'
