config {
  type: "table",
  schema: "dataform_poc_datalake",
  name: "complex_query",
  description: "This query finds questions with accepted answers and retrieves the answer and user details using a correlated subquery."
}

SELECT
    q.id AS question_id,
    q.title AS question_title,
    q.body AS question_body,
    a.id as answer_id,
    a.body as answer_body,
    (SELECT u.id FROM ${ref("users")} u WHERE u.id = a.owner_user_id) as user_id,
    (SELECT u.display_name FROM ${ref("users")} u WHERE u.id = a.owner_user_id) as user_display_name
FROM
    ${ref("posts_questions")} q
JOIN
    ${ref("posts_answers")} a on q.accepted_answer_id = a.id
WHERE
    q.accepted_answer_id IS NOT NULL