
config { type: "table" }

/**
 A more efficient transformation that joins questions and answers from the Stack Overflow dataset.
 */
SELECT
  q.title,
  q.body AS question_body,
  q.creation_date AS question_creation_date,
  a.body AS answer_body,
  a.creation_date AS answer_creation_date
FROM
  ${ref("posts_questions")} AS q
  JOIN ${ref("posts_answers")} AS a ON q.id = a.parent_id
WHERE
  q.score > 100
  AND q.answer_count >= 5
