config {
    type: "table",
    schema: "dataform_poc_datalake"
}

SELECT
    o.order_id,
    c.first_name,
    c.last_name,
    (o.quantity * 25.00) AS subtotal,
    (o.quantity * 25.00) * ${constants.TAX_RATE} AS estimated_tax,
    c.region
FROM
    ${ref("orders")} o
INNER JOIN  ${ref("customers")} c ON o.customer_id = c.customer_id
WHERE
    region IN ('${constants.VALID_REGIONS.join("', '")}')