config { type: "table" }

WITH user_questions AS (
    SELECT
        owner_user_id,
        COUNT(*) AS question_count
    FROM
        ${ref("posts_questions_source")}
    GROUP BY
        owner_user_id
),
user_answers AS (
    SELECT
        owner_user_id,
        COUNT(*) AS answer_count
    FROM
        ${ref("posts_answers_source")}
    GROUP BY
        owner_user_id
)
SELECT
    u.id AS user_id,
    u.display_name,
    u.reputation,
    COALESCE(uq.question_count, 0) AS question_count,
    COALESCE(ua.answer_count, 0) AS answer_count
FROM
    ${ref("users_source")} u
LEFT JOIN
    user_questions uq ON u.id = uq.owner_user_id
LEFT JOIN
    user_answers ua ON u.id = ua.owner_user_id
