config {
  type: "table",
  schema: "dataform_poc_datalake",
  name: "stackoverflow_transformed",
  description: "This table joins questions, answers, and users from the Stack Overflow dataset.",
  columns: {
    question_id: "The ID of the question.",
    question_title: "The title of the question.",
    question_body: "The body of the question.",
    answer_id: "The ID of the answer.",
    answer_body: "The body of the answer.",
    user_id: "The ID of the user who answered the question.",
    user_display_name: "The display name of the user."
  }
}

SELECT
  q.id AS question_id,
  q.title AS question_title,
  q.body AS question_body,
  a.id AS answer_id,
  a.body AS answer_body,
  u.id AS user_id,
  u.display_name AS user_display_name
FROM
  ${ref("posts_questions")} AS q
JOIN
  ${ref("posts_answers")} AS a
ON
  q.accepted_answer_id = a.id
JOIN
  ${ref("users")} AS u
ON
  a.owner_user_id = u.id
